PitStick: adc.h File Reference
adc.h File Reference
Contains ADC driver form one channel prototypes.
#include <stdint.h>
Macros
#define ADC_AVG (10u)
Functions
void Adc_Init (void)
Initialization of ADC+DMA.
uint16_t GetAdc_Voltage (void)
returns millivolts measuring of vbat
uint32_t getEntropy (void)
returns calculated entropy value
Detailed Description
Contains ADC driver form one channel prototypes.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
02-05-2016
Definition in file adc.h.
Macro Definition Documentation
ADC_AVG
#define ADC_AVG (10u)
Definition at line 13 of file adc.h.
Referenced by DMA1_Channel1_IRQHandler(), and GetAdcRaw().
Function Documentation
Adc_Init()
void Adc_Init (void)
Initialization of ADC+DMA.
Definition at line 19 of file adc.c.
References Adc_Buf.
Referenced by Init().
GetAdc_Voltage()
uint16_t GetAdc_Voltage (void)
returns millivolts measuring of vbat
Returns
Vbat(mV)
Definition at line 116 of file adc.c.
References GetAdcRaw().
Referenced by getPowerColor().
getEntropy()
uint32_t getEntropy (void)
returns calculated entropy value
Returns
value
Definition at line 93 of file adc.c.
References entropy.
Referenced by genRandom().