PitStick: adc.c File Reference
adc.c File Reference
Contains ADC driver for one channel.
#include <stm32f1xx.h>
#include "adc.h"
Functions
void Adc_Init (void)
Initialization of ADC+DMA.
void DMA1_Channel1_IRQHandler (void)
DMA ISR and "entropy" calcualations. Entropy is number of different adc readings for Vbat.
uint32_t getEntropy (void)
returns calculated entropy value
static uint16_t GetAdcRaw (void)
raw averaged value of adc channel reading
uint16_t GetAdc_Voltage (void)
returns millivolts measuring of vbat
Variables
static volatile uint16_t Adc_Buf [ADC_AVG]
static volatile uint32_t entropy = 0
Detailed Description
Contains ADC driver for one channel.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
18-11-2019
Version
1.10
Definition in file adc.c.
Function Documentation
Adc_Init()
void Adc_Init (void)
Initialization of ADC+DMA.
Definition at line 19 of file adc.c.
References Adc_Buf.
Referenced by Init().
DMA1_Channel1_IRQHandler()
void DMA1_Channel1_IRQHandler (void)
DMA ISR and "entropy" calcualations. Entropy is number of different adc readings for Vbat.
Definition at line 72 of file adc.c.
References ADC_AVG, Adc_Buf, and entropy.
GetAdc_Voltage()
uint16_t GetAdc_Voltage (void)
returns millivolts measuring of vbat
Returns
Vbat(mV)
Definition at line 116 of file adc.c.
References GetAdcRaw().
Referenced by getPowerColor().
GetAdcRaw()
static uint16_t GetAdcRaw (void) static
raw averaged value of adc channel reading
Returns
value
Definition at line 102 of file adc.c.
References ADC_AVG, and Adc_Buf.
Referenced by GetAdc_Voltage().
getEntropy()
uint32_t getEntropy (void)
returns calculated entropy value
Returns
value
Definition at line 93 of file adc.c.
References entropy.
Referenced by genRandom().
Variable Documentation
Adc_Buf
volatile uint16_t Adc_Buf[ADC_AVG] static
Definition at line 14 of file adc.c.
Referenced by Adc_Init(), DMA1_Channel1_IRQHandler(), and GetAdcRaw().
entropy
volatile uint32_t entropy = 0 static
Definition at line 66 of file adc.c.
Referenced by DMA1_Channel1_IRQHandler(), and getEntropy().