PitStick: bll.c File Reference
bll.c File Reference
Contains task switcher implementation and task table.
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "bll.h"
#include "heartbeat.h"
#include "clock.h"
#include "watchdog.h"
#include "buttons.h"
#include "led_control.h"
Data Structures
struct Task_table_t
Task table element.
Functions
static void ledControl_wrapper (void)
calls led_control function with ms as a parameter. ms is time from stick on to the current time
static void processButtons (void)
Polls the buttom.
uint8_t MainLoop_Iteration (void)
Contains main while(1) loop. Tasks are selected from the task table. Last task should be {0,0,NULL}. First parameter is period and the second is "phase" which is a remaining after dividing current time by the first param It's done to make switcher to use different timeslots.
Detailed Description
Contains task switcher implementation and task table.
Date
9-11-2019
Definition in file bll.c.
Function Documentation
ledControl_wrapper()
static void ledControl_wrapper (void) static
calls led_control function with ms as a parameter. ms is time from stick on to the current time
Definition at line 29 of file bll.c.
References led_control(), ReadTimer(), and ResetTimer().
Referenced by MainLoop_Iteration().
MainLoop_Iteration()
uint8_t MainLoop_Iteration (void)
Contains main while(1) loop. Tasks are selected from the task table. Last task should be {0,0,NULL}. First parameter is period and the second is "phase" which is a remaining after dividing current time by the first param It's done to make switcher to use different timeslots.
contains one iteration of the main loop
Returns
0 if no tick occured
Definition at line 54 of file bll.c.
References Counter, GetTicksCounter(), ledControl_wrapper(), processButtons(), Reset_Watchdog(), Task_table_t::Task, and Toggle_Heartbeat().
Referenced by main().
processButtons()
static void processButtons (void) static
Polls the buttom.
Definition at line 43 of file bll.c.
References B_CONFIG, and Button_Process().
Referenced by MainLoop_Iteration().