PitStick: bll.h File Reference
bll.h File Reference
Contains business logic function prototype.
#include <stdint.h>
Functions
uint8_t MainLoop_Iteration (void)
contains one iteration of the main loop
Detailed Description
Contains business logic function prototype.
Date
7-11-2019
Definition in file bll.h.
Function Documentation
MainLoop_Iteration()
uint8_t MainLoop_Iteration (void)
contains one iteration of the main loop
Returns
0 tick was not expired or 1 if tick expired.
contains one iteration of the main loop
Returns
0 if no tick occured
Definition at line 54 of file bll.c.
References Counter, GetTicksCounter(), ledControl_wrapper(), processButtons(), Reset_Watchdog(), Task_table_t::Task, and Toggle_Heartbeat().
Referenced by main().