PitStick: buttons.h File Reference
buttons.h File Reference
Buttons driver with debouncing and long press detection header file.
#include <stdint.h>
Macros
#define CALLS_PER_SECOND 100
number of Button_Process function call per second
#define BUTTONWAIT (CALLS_PER_SECOND / 20)
Number of tics to assume the button state is stable.
#define BUTTONLONGWAIT (CALLS_PER_SECOND * 2)
Number of tics to assume the button is long pressed.
Enumerations
enum Buttons_id_t { B_CONFIG = 0 , B_MAX }
Buttons id.
Functions
void Buttons_Init (void)
Initializes the buttons driver.
void Button_Process (uint8_t button_no)
Processes the button. Must be called from the timer interrupt.
void WaitButtonPress (Buttons_id_t button)
void WaitButtonRelease (Buttons_id_t button)
uint8_t IsPressed (Buttons_id_t button)
uint8_t IsShortPressed (Buttons_id_t button)
uint8_t IsSteadyReleased (Buttons_id_t button)
uint8_t IsReleased (Buttons_id_t button)
uint8_t IsLongPressed (Buttons_id_t button)
uint8_t IsSteadyPressed (Buttons_id_t button)
Detailed Description
Buttons driver with debouncing and long press detection header file.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Author
Mykhaylo Shcherbak
Date
29-08-2016
Version
1.00
Definition in file buttons.h.
Macro Definition Documentation
BUTTONLONGWAIT
#define BUTTONLONGWAIT (CALLS_PER_SECOND * 2)
Number of tics to assume the button is long pressed.
Definition at line 26 of file buttons.h.
Referenced by Button_Process().
BUTTONWAIT
#define BUTTONWAIT (CALLS_PER_SECOND / 20)
Number of tics to assume the button state is stable.
Definition at line 22 of file buttons.h.
Referenced by Button_Process().
CALLS_PER_SECOND
#define CALLS_PER_SECOND 100
number of Button_Process function call per second
Definition at line 15 of file buttons.h.
Enumeration Type Documentation
Buttons_id_t
enum Buttons_id_t
Buttons id.
Enumerator
B_CONFIG
The single button
B_MAX
Maximum number of buttons
Definition at line 31 of file buttons.h.
Function Documentation
Button_Process()
void Button_Process (uint8_t button_no)
Processes the button. Must be called from the timer interrupt.
Parameters
button_no The button number.
Referenced by processButtons().
Buttons_Init()
void Buttons_Init (void)
Initializes the buttons driver.
Definition at line 104 of file buttons.c.
References b, B_MAX, Buttons_t::buttonFunc, Buttons, Pressed, Released, and Buttons_t::state.
Referenced by Init().
IsLongPressed()
uint8_t IsLongPressed (Buttons_id_t button)
Check if button is long pressed
Definition at line 154 of file buttons.c.
References Buttons, LongPressed, NotExists, and Buttons_t::state.
Referenced by changeParam().
IsPressed()
uint8_t IsPressed (Buttons_id_t button)
Check for button is pressed without debouncing
Definition at line 129 of file buttons.c.
References Buttons, LongPressed, NotExists, Pressed, Buttons_t::state, and SteadyPressed.
Referenced by changeParam(), and led_control().
IsReleased()
uint8_t IsReleased (Buttons_id_t button)
Check for button is released without debouncing
Definition at line 148 of file buttons.c.
References Buttons, LongReleased, NotExists, Released, Buttons_t::state, and SteadyReleased.
IsShortPressed()
uint8_t IsShortPressed (Buttons_id_t button)
Check for the button is pressed but not long pressed without debouncing
Definition at line 135 of file buttons.c.
References Buttons, NotExists, Pressed, Buttons_t::state, and SteadyPressed.
IsSteadyPressed()
uint8_t IsSteadyPressed (Buttons_id_t button)
Check if button is pressed with debouncing
Definition at line 160 of file buttons.c.
References Buttons, LongPressed, NotExists, Buttons_t::state, and SteadyPressed.
IsSteadyReleased()
uint8_t IsSteadyReleased (Buttons_id_t button)
Check for button is released with debouncing
Definition at line 142 of file buttons.c.
References Buttons, LongReleased, NotExists, Buttons_t::state, and SteadyReleased.
WaitButtonPress()
void WaitButtonPress (Buttons_id_t button)
Wait for button is pressed (with debouncing)
Definition at line 116 of file buttons.c.
References Buttons, LongPressed, NotExists, and SteadyPressed.
WaitButtonRelease()
void WaitButtonRelease (Buttons_id_t button)
Wait for button is released (with debouncing)
Definition at line 122 of file buttons.c.
References Buttons, LongReleased, NotExists, and SteadyReleased.