PitStick: buttons.c File Reference
buttons.c File Reference
Buttons driver with debouncing and long press detection.
#include <stdint.h>
#include "buttons.h"
#include "gpio.h"
Data Structures
struct Buttons_t
The button description.
Typedefs
typedef uint8_t(* pButtonFunc_t) (void)
Enumerations
enum ButtonState {
NotExists =0, Pressed, Released, SteadyPressed,
SteadyReleased, LongPressed, LongReleased
}
describes the current state of the button
Functions
static uint8_t ButtonState (void)
void Button_Process (const Buttons_id_t Button_id)
void Buttons_Init (void)
Initializes the buttons driver.
void WaitButtonPress (Buttons_id_t button)
void WaitButtonRelease (Buttons_id_t button)
uint8_t IsPressed (Buttons_id_t button)
uint8_t IsShortPressed (Buttons_id_t button)
uint8_t IsSteadyReleased (Buttons_id_t button)
uint8_t IsReleased (Buttons_id_t button)
uint8_t IsLongPressed (Buttons_id_t button)
uint8_t IsSteadyPressed (Buttons_id_t button)
Variables
static volatile Buttons_t Buttons [B_MAX] ={{Released,ButtonState,0}}
Button state array.
Detailed Description
Buttons driver with debouncing and long press detection.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Author
Mykhaylo Shcherbak
Date
29-08-2016
Version
1.00
Definition in file buttons.c.
Typedef Documentation
pButtonFunc_t
typedef uint8_t(* pButtonFunc_t) (void)
Definition at line 26 of file buttons.c.
Enumeration Type Documentation
ButtonState
enum ButtonState
describes the current state of the button
Enumerator
NotExists
NotExists.
No such button. Ignore all functions
Pressed
Pressed.
Just pressed
Released
Released.
Just released
SteadyPressed
SteadyPressed.
Steady pressed. Debouncing period passed
SteadyReleased
SteadyReleased.
Steady released. Debouncing period passed
LongPressed
LongPressed.
Long pressed
LongReleased
LongReleased.
Long released. Unused in BL
Definition at line 17 of file buttons.c.
Function Documentation
Button_Process()
void Button_Process (const Buttons_id_t Button_id)
Definition at line 47 of file buttons.c.
References Buttons_t::buttonFunc, BUTTONLONGWAIT, BUTTONWAIT, Buttons_t::count, LongPressed, LongReleased, NotExists, Pressed, Released, Buttons_t::state, SteadyPressed, and SteadyReleased.
Buttons_Init()
void Buttons_Init (void)
Initializes the buttons driver.
Definition at line 104 of file buttons.c.
References b, B_MAX, Buttons_t::buttonFunc, Pressed, Released, and Buttons_t::state.
Referenced by Init().
ButtonState()
static uint8_t ButtonState (void) static
Definition at line 37 of file buttons.c.
References GPIO_BUTTON, and Gpio_Read_Bit().
IsLongPressed()
uint8_t IsLongPressed (Buttons_id_t button)
Check if button is long pressed
Definition at line 154 of file buttons.c.
References LongPressed, NotExists, and Buttons_t::state.
Referenced by changeParam().
IsPressed()
uint8_t IsPressed (Buttons_id_t button)
Check for button is pressed without debouncing
Definition at line 129 of file buttons.c.
References LongPressed, NotExists, Pressed, Buttons_t::state, and SteadyPressed.
Referenced by changeParam(), and led_control().
IsReleased()
uint8_t IsReleased (Buttons_id_t button)
Check for button is released without debouncing
Definition at line 148 of file buttons.c.
References LongReleased, NotExists, Released, Buttons_t::state, and SteadyReleased.
IsShortPressed()
uint8_t IsShortPressed (Buttons_id_t button)
Check for the button is pressed but not long pressed without debouncing
Definition at line 135 of file buttons.c.
References NotExists, Pressed, Buttons_t::state, and SteadyPressed.
IsSteadyPressed()
uint8_t IsSteadyPressed (Buttons_id_t button)
Check if button is pressed with debouncing
Definition at line 160 of file buttons.c.
References LongPressed, NotExists, Buttons_t::state, and SteadyPressed.
IsSteadyReleased()
uint8_t IsSteadyReleased (Buttons_id_t button)
Check for button is released with debouncing
Definition at line 142 of file buttons.c.
References LongReleased, NotExists, Buttons_t::state, and SteadyReleased.
WaitButtonPress()
void WaitButtonPress (Buttons_id_t button)
Wait for button is pressed (with debouncing)
Definition at line 116 of file buttons.c.
References LongPressed, NotExists, and SteadyPressed.
WaitButtonRelease()
void WaitButtonRelease (Buttons_id_t button)
Wait for button is released (with debouncing)
Definition at line 122 of file buttons.c.
References LongReleased, NotExists, and SteadyReleased.
Variable Documentation
Buttons
volatile Buttons_t Buttons[B_MAX] ={{Released,ButtonState,0}} static
Button state array.
Definition at line 45 of file buttons.c.