PitStick: clock.c File Reference
clock.c File Reference
Contains clock init and functions.
#include "stm32f1xx.h"
#include "clock.h"
#include "gpio.h"
Functions
void Clock_HSE_Init (void)
Inits HSE as a main clock. PLL is setup to *9.
void Systick_Init (void)
Inits systick timer interrupt for 1ms period.
void SysTick_Handler (void)
void ResetTimer (uint32_t *const Timer)
Resets software timer.
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
uint32_t ReadTimer (uint32_t *const Timer)
uint32_t GetTicksCounter (void)
Returns number of milliseconds from timebase start.
Detailed Description
Contains clock init and functions.
Author
Mikl Scherbak (mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om)
Date
7-04-2016
Version
1.0
Definition in file clock.c.
Function Documentation
void Clock_HSE_Init (void)
Inits HSE as a main clock. PLL is setup to *9.
Inits HSE as a main clock. PLL is setup to *8.
Definition at line 17 of file clock.c.
uint32_t GetTicksCounter (void)
Returns number of milliseconds from timebase start.
Returns
milliscenonds
Definition at line 81 of file clock.c.
Referenced by MainLoop_Iteration().
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
Parameters
Timer Timer variable
Timeout Timeout value in ms
Returns
zero if timer has not expired, non-zero else
Definition at line 71 of file clock.c.
Referenced by blinkTwice().
uint32_t ReadTimer (uint32_t *const Timer)
Definition at line 76 of file clock.c.
void ResetTimer (uint32_t *const Timer)
Resets software timer.
Parameters
Timer timer variable
Definition at line 60 of file clock.c.
Referenced by blinkTwice().
void SysTick_Handler (void)
Definition at line 51 of file clock.c.
Referenced by Systick_Init().
void Systick_Init (void)
Inits systick timer interrupt for 1ms period.
Definition at line 44 of file clock.c.
References CPU_FREQ, SYSTICK_FREQ, and SysTick_Handler().