PitStick: clock.h File Reference
clock.h File Reference
Contains definitions for clock.c.
#include <stdint.h>
Macros
#define CPU_FREQ 64000000ul
#define SYSTICK_FREQ 1000
Functions
void Clock_HSE_Init (void)
Inits HSE as a main clock. PLL is setup to *8.
uint32_t GetTicksCounter (void)
Returns number of milliseconds from timebase start.
void Systick_Init (void)
Inits systick timer interrupt for 1ms period.
void ResetTimer (uint32_t *const Timer)
Resets software timer.
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
uint32_t ReadTimer (uint32_t *const Timer)
Detailed Description
Contains definitions for clock.c.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
07-04-2016
Version
1.0
Definition in file clock.h.
Macro Definition Documentation
CPU_FREQ
#define CPU_FREQ 64000000ul
Definition at line 14 of file clock.h.
Referenced by Systick_Init().
SYSTICK_FREQ
#define SYSTICK_FREQ 1000
Definition at line 15 of file clock.h.
Referenced by Systick_Init().
Function Documentation
Clock_HSE_Init()
void Clock_HSE_Init (void)
Inits HSE as a main clock. PLL is setup to *8.
Inits HSE as a main clock. PLL is setup to *8.
Definition at line 17 of file clock.c.
Referenced by Init().
GetTicksCounter()
uint32_t GetTicksCounter (void)
Returns number of milliseconds from timebase start.
Returns
milliscenonds
Definition at line 81 of file clock.c.
References Counter.
Referenced by MainLoop_Iteration().
IsExpiredTimer()
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
Parameters
Timer Timer variable
Timeout Timeout value in ms
Returns
zero if timer has not expired, non-zero else
Definition at line 71 of file clock.c.
References Counter.
Referenced by blink(), blinkTwice(), changeParam(), green2Black(), greenPhase(), ironB1_29(), ironC1_10(), lock(), oneByOneBlue(), oneByOneGreen(), scMode(), tlight(), tlightForward(), tlightPre(), tlightReverse(), tlightTMain(), and yellowPhase().
ReadTimer()
uint32_t ReadTimer (uint32_t *const Timer)
Definition at line 76 of file clock.c.
References Counter.
Referenced by ledControl_wrapper().
ResetTimer()
void ResetTimer (uint32_t *const Timer)
Resets software timer.
Parameters
Timer timer variable
Definition at line 60 of file clock.c.
References Counter.
Referenced by blink(), blinkTwice(), changeParam(), config(), green2Black(), greenPhase(), ironB1_29(), ironC1_10(), ledControl_wrapper(), lock(), oneByOneBlue(), oneByOneGreen(), scMode(), tlight(), tlightForward(), tlightPre(), tlightReverse(), tlightTMain(), and yellowPhase().
Systick_Init()
void Systick_Init (void)
Inits systick timer interrupt for 1ms period.
Definition at line 44 of file clock.c.
References CPU_FREQ, and SYSTICK_FREQ.
Referenced by Init().