PitStick: eeemu.c File Reference
eeemu.c File Reference
eeprom emulation implementation
#include "eeemu.h"
#include <stdint.h>
#include <string.h>
#include "stm32f1xx.h"
Data Structures
struct eeemu_storage_s
Storage element structure.
union eeemu_storage_t
union for the storage element
Enumerations
enum { MAXSTORAGE = 1024/sizeof(eeemu_storage_t), DEFAULT_VALUE = 0, SEED_NOT_INITED = 0xFFFF }
Functions
static volatile eeemu_storage_t __attribute__ ((__section__(".eeemu")))
flash page for holding configs
static uint8_t crc8 (uint8_t *data, uint8_t const len)
crc8 calcualation for data block
static void eeemuErasePage (uint32_t const addr)
Erasing a flash page.
static uint16_t getCurrentSeedIdx (void)
Searching for the last stored prng.
void eeemu_write (uint8_t *const values)
stores config block to the eeprom emulation page
void eeemu_Init (void)
Eeprom emulation subsystem init. It finds the index of the last saved config.
uint8_t * eeemuGetValue (void)
returns the pointer to the last stored configuration. Size is MAX_STORED
uint16_t eeemuSeedGet (void)
Returns previous saved prng value.
void eeemuSeedSet (const uint16_t seed)
Saves current prng.
Detailed Description
eeprom emulation implementation
This file contains functions implementation for eeprom emulation. There are two types of the storage
Config
PRNG current value
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
19-11-2019
Version
1.00
Definition in file eeemu.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAXSTORAGE
Maximum number of storage elements in the page
DEFAULT_VALUE
Default values for the storage elements
SEED_NOT_INITED
Value to find first uninited element for seed storage. seed/prng is 15bits long so 0xFFFF is not a valid number
Definition at line 37 of file eeemu.c.
Function Documentation
__attribute__()
static volatile eeemu_storage_t __attribute__ ((__section__(".eeemu"))) static
flash page for holding configs
Waiting for flash write operation complete
Definition at line 47 of file eeemu.c.
crc8()
static uint8_t crc8 (uint8_t * data, uint8_t const len) static
crc8 calcualation for data block
Parameters
data data itself
len data length
Returns
crc8
Definition at line 72 of file eeemu.c.
Referenced by eeemu_Init(), and eeemu_write().
eeemu_Init()
void eeemu_Init (void)
Eeprom emulation subsystem init. It finds the index of the last saved config.
Definition at line 157 of file eeemu.c.
References crc8(), MAX_STORED, and MAXSTORAGE.
Referenced by Init().
eeemu_write()
void eeemu_write (uint8_t *const value)
stores config block to the eeprom emulation page
Parameters
value pointer to the block of values. Size is MAX_STORED
Definition at line 123 of file eeemu.c.
References eeemu_storage_s::crc8, crc8(), eeemuErasePage(), MAX_STORED, MAXSTORAGE, eeemu_storage_t::raw, eeemu_storage_s::stored, and eeemu_storage_t::structured.
Referenced by config().
eeemuErasePage()
static void eeemuErasePage (uint32_t const addr) static
Erasing a flash page.
Parameters
addr flash page addr
Definition at line 92 of file eeemu.c.
Referenced by eeemu_write(), and eeemuSeedSet().
eeemuGetValue()
uint8_t* eeemuGetValue (void)
returns the pointer to the last stored configuration. Size is MAX_STORED
Definition at line 171 of file eeemu.c.
References DEFAULT_VALUE, and MAX_STORED.
Referenced by config(), led_control(), lock(), pitStopCalc(), podnosMode(), tlightMode(), and tlightTMain().
eeemuSeedGet()
uint16_t eeemuSeedGet (void)
Returns previous saved prng value.
Returns
the value
Definition at line 184 of file eeemu.c.
References getCurrentSeedIdx(), and SEED_NOT_INITED.
Referenced by genRandom().
eeemuSeedSet()
void eeemuSeedSet (const uint16_t seed)
Saves current prng.
Parameters
seed the value
Definition at line 190 of file eeemu.c.
References eeemuErasePage(), getCurrentSeedIdx(), and SEED_NOT_INITED.
Referenced by genRandom().
getCurrentSeedIdx()
static uint16_t getCurrentSeedIdx (void) static
Searching for the last stored prng.
Returns
last stored value or SEED_NOT_INITED if nothing is stored
Definition at line 109 of file eeemu.c.
References SEED_NOT_INITED.
Referenced by eeemuSeedGet(), and eeemuSeedSet().