PitStick: eeemu.h File Reference
eeemu.h File Reference
eeprom emulation header in pair with eeemu.c
#include <stdint.h>
Macros
#define MAX_STORED 9
Functions
void eeemu_Init (void)
Eeprom emulation subsystem init. It finds the index of the last saved config.
uint8_t * eeemuGetValue (void)
returns the pointer to the last stored configuration. Size is MAX_STORED
void eeemu_write (uint8_t *const value)
stores config block to the eeprom emulation page
uint16_t eeemuSeedGet (void)
Returns previous saved prng value.
void eeemuSeedSet (const uint16_t seed)
Saves current prng.
Detailed Description
eeprom emulation header in pair with eeemu.c
This file contains functions prototypes for eeprom emulation. There are two types of the storage
Config
PRNG current value
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
19-11-2019
Version
1.00
Definition in file eeemu.h.
Macro Definition Documentation
MAX_STORED
#define MAX_STORED 9
The number of stored params. All params are one byte size
Definition at line 15 of file eeemu.h.
Referenced by config(), eeemu_Init(), eeemu_write(), and eeemuGetValue().
Function Documentation
eeemu_Init()
void eeemu_Init (void)
Eeprom emulation subsystem init. It finds the index of the last saved config.
Definition at line 157 of file eeemu.c.
References crc8(), MAX_STORED, and MAXSTORAGE.
Referenced by Init().
eeemu_write()
void eeemu_write (uint8_t *const value)
stores config block to the eeprom emulation page
Parameters
value pointer to the block of values. Size is MAX_STORED
Definition at line 123 of file eeemu.c.
References crc8(), eeemu_storage_s::crc8, eeemuErasePage(), MAX_STORED, MAXSTORAGE, eeemu_storage_t::raw, eeemu_storage_s::stored, and eeemu_storage_t::structured.
Referenced by config().
eeemuGetValue()
uint8_t * eeemuGetValue (void)
returns the pointer to the last stored configuration. Size is MAX_STORED
Definition at line 171 of file eeemu.c.
References DEFAULT_VALUE, and MAX_STORED.
Referenced by config(), led_control(), lock(), pitInviteMode(), pitStopCalc(), podnosMode(), tlightMode(), and tlightTMain().
eeemuSeedGet()
uint16_t eeemuSeedGet (void)
Returns previous saved prng value.
Returns
the value
Definition at line 184 of file eeemu.c.
References getCurrentSeedIdx(), and SEED_NOT_INITED.
Referenced by genRandom().
eeemuSeedSet()
void eeemuSeedSet (const uint16_t seed)
Saves current prng.
Parameters
seed the value
Definition at line 190 of file eeemu.c.
References eeemuErasePage(), getCurrentSeedIdx(), and SEED_NOT_INITED.
Referenced by genRandom().