PitStick: gpio.h File Reference
gpio.h File Reference
Contains definitions for gpio.c.
#include "stm32f1xx.h"
Enumerations
enum Gpio_Desc_t { GPIO_HEARTBEAT = 0 , GPIO_WS_OUT , GPIO_BUTTON , GPIO_TOTAL }
Descriptions of GPIO pins.
Functions
void Gpio_Init (void)
void Gpio_Set_Bit (Gpio_Desc_t Gpio)
Sets the corresponding GPIO pin.
void Gpio_Clear_Bit (Gpio_Desc_t Gpio)
Reads the corresponding GPIO pin.
uint8_t Gpio_Read_Bit (Gpio_Desc_t Gpio)
void Gpio_Get_Alt_PortPin (const Gpio_Desc_t Gpio, GPIO_TypeDef **const Port, uint8_t *const Pin)
returns pin and port for selected AF GPIO
Detailed Description
Contains definitions for gpio.c.
Date
12-04-2016
Author
Mikl Scherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Version
1.0
Definition in file gpio.h.
Enumeration Type Documentation
Gpio_Desc_t
enum Gpio_Desc_t
Descriptions of GPIO pins.
Enumerator
GPIO_HEARTBEAT
HEARTBEAT led
GPIO_WS_OUT
Led strip out
GPIO_BUTTON
Button in
GPIO_TOTAL
Total number of GPIOs
Definition at line 18 of file gpio.h.
Function Documentation
Gpio_Clear_Bit()
void Gpio_Clear_Bit (Gpio_Desc_t Gpio)
Reads the corresponding GPIO pin.
Parameters
Gpio pin
Definition at line 99 of file gpio.c.
References Gpio_Config, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Toggle_Heartbeat().
Gpio_Get_Alt_PortPin()
void Gpio_Get_Alt_PortPin (const Gpio_Desc_t Gpio, GPIO_TypeDef **const Port, uint8_t *const Pin)
returns pin and port for selected AF GPIO
Parameters
Gpio pin id
Port Pointer where port pointer will be placed. Must not be NULL
Pin Pointer where pin number will be placed. Must not be NULL
Definition at line 124 of file gpio.c.
References Gpio_Config, GPIO_MODE_DO_NOT_TOUCH, GPIO_TOTAL, Gpio_Config_t::Pin, and Gpio_Config_t::Port.
Referenced by pin_init().
Gpio_Init()
void Gpio_Init (void)
Definition at line 40 of file gpio.c.
References Gpio_Config, GPIO_MODE_IN, GPIO_MODE_OUT, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Init().
Gpio_Read_Bit()
uint8_t Gpio_Read_Bit (Gpio_Desc_t Gpio)
Definition at line 107 of file gpio.c.
References Gpio_Config, and GPIO_TOTAL.
Gpio_Set_Bit()
void Gpio_Set_Bit (Gpio_Desc_t Gpio)
Sets the corresponding GPIO pin.
Parameters
Gpio pin
Definition at line 91 of file gpio.c.
References Gpio_Config, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Toggle_Heartbeat().