PitStick: gpio.c File Reference
gpio.c File Reference
Contains init and access functions for Gpio.
#include <stddef.h>
#include "stm32f1xx.h"
#include "gpio.h"
Data Structures
struct Gpio_Config_t
Gpio pin configuration.
Enumerations
enum Gpio_Mode_t { GPIO_MODE_IN =0 , GPIO_MODE_OUT , GPIO_MODE_DO_NOT_TOUCH }
Functions
void Gpio_Init (void)
void Gpio_Set_Bit (Gpio_Desc_t Gpio)
Sets the corresponding GPIO pin.
void Gpio_Clear_Bit (Gpio_Desc_t Gpio)
Reads the corresponding GPIO pin.
uint8_t Gpio_Read_Bit (Gpio_Desc_t Gpio)
void Gpio_Get_Alt_PortPin (const Gpio_Desc_t Gpio, GPIO_TypeDef **const Port, uint8_t *const Pin)
returns pin and port for selected AF GPIO
Variables
static const Gpio_Config_t Gpio_Config [GPIO_TOTAL]
Detailed Description
Contains init and access functions for Gpio.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
14-01-2019
Version
1.1
Definition in file gpio.c.
Enumeration Type Documentation
Gpio_Mode_t
enum Gpio_Mode_t
Enumerator
GPIO_MODE_IN
GPIO_MODE_OUT
GPIO_MODE_DO_NOT_TOUCH
Definition at line 15 of file gpio.c.
Function Documentation
Gpio_Clear_Bit()
void Gpio_Clear_Bit (Gpio_Desc_t Gpio)
Reads the corresponding GPIO pin.
Parameters
Gpio pin
Definition at line 99 of file gpio.c.
References Gpio_Config, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Toggle_Heartbeat().
Gpio_Get_Alt_PortPin()
void Gpio_Get_Alt_PortPin (const Gpio_Desc_t Gpio, GPIO_TypeDef **const Port, uint8_t *const Pin)
returns pin and port for selected AF GPIO
Parameters
Gpio pin id
Port Pointer where port pointer will be placed. Must not be NULL
Pin Pointer where pin number will be placed. Must not be NULL
Definition at line 124 of file gpio.c.
References Gpio_Config, GPIO_MODE_DO_NOT_TOUCH, GPIO_TOTAL, Gpio_Config_t::Pin, and Gpio_Config_t::Port.
Referenced by pin_init().
Gpio_Init()
void Gpio_Init (void)
Definition at line 40 of file gpio.c.
References Gpio_Config, GPIO_MODE_IN, GPIO_MODE_OUT, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Init().
Gpio_Read_Bit()
uint8_t Gpio_Read_Bit (Gpio_Desc_t Gpio)
Definition at line 107 of file gpio.c.
References Gpio_Config, and GPIO_TOTAL.
Gpio_Set_Bit()
void Gpio_Set_Bit (Gpio_Desc_t Gpio)
Sets the corresponding GPIO pin.
Parameters
Gpio pin
Definition at line 91 of file gpio.c.
References Gpio_Config, GPIO_TOTAL, and Gpio_Config_t::Port.
Referenced by Toggle_Heartbeat().
Variable Documentation
Gpio_Config
const Gpio_Config_t Gpio_Config[GPIO_TOTAL] static
Initial value:
=
{
        [GPIO_WS_OUT]       = {.Port = GPIOA,.Pin = 0,  .Mode = GPIO_MODE_DO_NOT_TOUCH},
        [GPIO_BUTTON]       = {.Port = GPIOA,.Pin = 2,  .Mode = GPIO_MODE_IN},
        [GPIO_HEARTBEAT]    = {.Port = GPIOC,.Pin = 13, .Mode = GPIO_MODE_OUT   }
}
Definition at line 33 of file gpio.c.
Referenced by Gpio_Clear_Bit(), Gpio_Get_Alt_PortPin(), Gpio_Init(), Gpio_Read_Bit(), and Gpio_Set_Bit().