PitStick: heartbeat.c File Reference
heartbeat.c File Reference
Contains heartbeat toggling function.
#include <stdint.h>
#include "heartbeat.h"
#include "gpio.h"
Functions
void Toggle_Heartbeat (void)
Toggles "Heartbeat led".
Detailed Description
Contains heartbeat toggling function.
Date
11-11-2019
Definition in file heartbeat.c.
Function Documentation
Toggle_Heartbeat()
void Toggle_Heartbeat (void)
Toggles "Heartbeat led".
Definition at line 10 of file heartbeat.c.
References Gpio_Clear_Bit(), GPIO_HEARTBEAT, and Gpio_Set_Bit().
Referenced by MainLoop_Iteration().