PitStick: led_strip.c File Reference
led_strip.c File Reference
Contains common functions implementations for led strip control.
#include <stddef.h>
#include "led_strip.h"
#include "project_conf.h"
#include "clock.h"
#include "rgbw.h"
Data Structures
struct Strip_t
Strip description. Is used for traffic light emulation.
struct Div_t
brightness level descriptor. For fractional numbers multiplier and divider is used.
Enumerations
enum BlinkTwice_t { BLINKTWICE_BLINK , BLINKTWICE_OFF }
Functions
static uint8_t getBrightness (void)
static void applyBrightness (const Led_t *const in, Led_t *const out)
Applies current brightness level to the led values.
static void displayDigit (const Colors_t color, uint8_t digit, uint8_t column)
Displays one digit as a led column. Each 3 leds are separated by a black one.
void setBrightness (const uint8_t brighness_a)
Set the current brightness. All operations for now on will be performed at this brightness until it is changed by this function.
void putPixel (const uint8_t row, const uint8_t pos, const Colors_t color)
Puts a pixel to the out buffer. Does not change the led color until updated.
void put2pixels (const Colors_t color, const uint8_t pos)
Puts two pixels at the same position in both rows. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
void showFull (const Colors_t color)
Fills the whole stick by the color. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
uint8_t showFullWithInit (const Colors_t color, const uint8_t init)
Shows total stick with the same color if init is nonzero. Does nothing else.
void displayNumber (const Colors_t colorL, const Colors_t colorR, const uint8_t Number)
Displays a number as two bars. One for tens and the other for ones. Leds in the bars are separated by one black led per each 3.
void dispStrip (const Colors_t color, const uint8_t stripNo)
displays strip number (0 - 4) of selected color
void dispStrips (const Colors_t color, const uint8_t nstrips)
Displays strips (0 - 5) of selected color. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
void dispStripsRevese (const Colors_t color, const uint8_t nstrips)
Displays strips (0 - 5) of selected color starting from the handle. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
void fill2Pixels (const Colors_t _color, const uint8_t _from, const uint8_t _to)
uint8_t blinkTwice (const uint8_t init, const Colors_t color, pPowerColorFunc_t const getPowerColor)
Blinks the whole stick by color to black two times at 1Hz frequency.
uint8_t blink (const uint8_t init, const Blink_t *const _blink)
Blinks between the _blink.pOnPhase function out and _blink.pOffPhase.
void sendDataToStrip (void)
Sends the led buffer to the led strip.
Variables
static uint8_t Brightness = 0
The current brightness level.
static const Led_t colors []
Color names to values conversion.
static Led_t leds [NLEDS]
Buffer for storing led pixel data.
Detailed Description
Contains common functions implementations for led strip control.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
20-11-2019
Version
1.00
Definition in file led_strip.c.
Enumeration Type Documentation
BlinkTwice_t
enum BlinkTwice_t
Enumerator
BLINKTWICE_BLINK
State while stick is blinking
BLINKTWICE_OFF
State after the stick blinked and goes off
Definition at line 261 of file led_strip.c.
Function Documentation
applyBrightness()
static void applyBrightness (const Led_t *const in, Led_t *const out) static
Applies current brightness level to the led values.
Parameters
in Input led data
out Calculated led data
Definition at line 75 of file led_strip.c.
References Led_t::B, Div_t::div, Led_t::G, getBrightness(), MAX_BRIGHNESS_LEVELS, Div_t::mul, Led_t::R, and Led_t::W.
Referenced by displayDigit(), putPixel(), and showFull().
blink()
uint8_t blink (const uint8_t init, const Blink_t *const _blink)
Blinks between the _blink.pOnPhase function out and _blink.pOffPhase.
Parameters
init != 0 if the function is called first time
_blink the structure that contains timings and callback
Returns
!0 if buffer was changed
Definition at line 324 of file led_strip.c.
References IsExpiredTimer(), Blink_t::off, Blink_t::on, Blink_t::pOffPhase, Blink_t::pOnPhase, and ResetTimer().
Referenced by allGreenBlink(), allRedBlink(), darkPhase(), ironB30(), and ironC11().
blinkTwice()
uint8_t blinkTwice (const uint8_t init, const Colors_t color, pPowerColorFunc_t const getPowerColor)
Blinks the whole stick by color to black two times at 1Hz frequency.
Parameters
[in] init nonzero value shows that this is the first iteration of this function
[in] color The color index when the stick is on
[in] getPowerColor function that returns the color number corresponding to the current batt level
Returns
if nonzero the strip must be updated by sendDataToStrip
Definition at line 267 of file led_strip.c.
References BLACK, BLINKTWICE_BLINK, BLINKTWICE_OFF, getPowerColor(), IsExpiredTimer(), put2pixels(), ResetTimer(), and showFull().
Referenced by lastGreenPhase(), redPre(), and yellowTPre().
displayDigit()
static void displayDigit (const Colors_t color, uint8_t digit, uint8_t column) static
Displays one digit as a led column. Each 3 leds are separated by a black one.
Parameters
color Color index
digit The digit to display. It may not be a real (0-9) digit but more.
column Column where to display
Definition at line 101 of file led_strip.c.
References applyBrightness(), BLACK, colors, leds, and NLEDS.
Referenced by displayNumber().
displayNumber()
void displayNumber (const Colors_t colorL, const Colors_t colorR, const uint8_t Number)
Displays a number as two bars. One for tens and the other for ones. Leds in the bars are separated by one black led per each 3.
Parameters
colorL Color index for tens
colorR Color index for ones
Number The number to display
Definition at line 199 of file led_strip.c.
References displayDigit().
Referenced by displayPodnosModeTime(), displayT1(), displayT2(), displayTlightMax(), displayTlightMin(), and displayTSEQ().
dispStrip()
void dispStrip (const Colors_t color, const uint8_t stripNo)
displays strip number (0 - 4) of selected color
Parameters
color color
stripNo number of strip (0 - 4)
Definition at line 205 of file led_strip.c.
References Strip_t::number, and put2pixels().
Referenced by displayPitInviteColor(), dispStrips(), dispStripsRevese(), pitInviteMode(), show1245(), show15(), and show234().
dispStrips()
void dispStrips (const Colors_t color, const uint8_t nstrips)
Displays strips (0 - 5) of selected color. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
Parameters
color Color index
nstrips Number of strips
Definition at line 223 of file led_strip.c.
References BLACK, dispStrip(), and showFull().
Referenced by dispRedStrips(), and dispYellowStrips().
dispStripsRevese()
void dispStripsRevese (const Colors_t color, const uint8_t nstrips)
Displays strips (0 - 5) of selected color starting from the handle. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
Parameters
color Color index
nstrips Number of strips
Definition at line 232 of file led_strip.c.
References BLACK, dispStrip(), and showFull().
Referenced by dispRedStripsReverse().
fill2Pixels()
void fill2Pixels (const Colors_t _color, const uint8_t _from, const uint8_t _to)
Definition at line 242 of file led_strip.c.
References put2pixels().
Referenced by fill2PixelsWithFade(), and tlightPre().
getBrightness()
static uint8_t getBrightness (void) inline static
Definition at line 65 of file led_strip.c.
References Brightness.
Referenced by applyBrightness().
put2pixels()
void put2pixels (const Colors_t color, const uint8_t pos)
Puts two pixels at the same position in both rows. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
Parameters
color Color index
pos Position (0 - NLEDS / 2 - 1)
Definition at line 171 of file led_strip.c.
References putPixel().
Referenced by blinkTwice(), changeParam(), config(), dispBrighnessPattern(), dispModePattern(), dispStrip(), fill2Pixels(), fill2PixelsWithFade(), green2Black(), greenPhase(), ironB1_29(), ironC1_10(), lock(), oneByOneBlue(), oneByOneGreen(), pitInviteMode(), and showPower().
putPixel()
void putPixel (const uint8_t row, const uint8_t pos, const Colors_t color)
Puts a pixel to the out buffer. Does not change the led color until updated.
Parameters
row Row number (0-1)
pos Position (0-NLEDS / 2 - 1)
color Color index
Definition at line 152 of file led_strip.c.
References applyBrightness(), colors, leds, and NLEDS.
Referenced by dispModePattern(), ironB30row(), ironC11green(), and put2pixels().
sendDataToStrip()
void sendDataToStrip (void)
Sends the led buffer to the led strip.
Definition at line 361 of file led_strip.c.
References displayStrip(), and leds.
Referenced by led_control().
setBrightness()
void setBrightness (const uint8_t brighness_a)
Set the current brightness. All operations for now on will be performed at this brightness until it is changed by this function.
Parameters
brighness_a The brighness level (0-3 for now).
Definition at line 140 of file led_strip.c.
References Brightness, and MAX_BRIGHNESS_LEVELS.
Referenced by config(), led_control(), and lock().
showFull()
void showFull (const Colors_t color)
Fills the whole stick by the color. Data is put to the out buffer and actual color will not be changed until updated by sendDataToStrip.
Parameters
color Color index
Definition at line 178 of file led_strip.c.
References applyBrightness(), colors, leds, and NLEDS.
Referenced by blinkTwice(), changeParam(), config(), dispBrighnessPattern(), displayPitInviteColor(), dispModePattern(), dispStrips(), dispStripsRevese(), green2Black(), greenPhase(), ironB1_29(), ironB30row(), ironC11green(), ironC1_10(), lock(), oneByOneBlue(), oneByOneGreen(), pitInviteMode(), show1245(), show15(), show234(), showFullWithInit(), showPower(), tlightPre(), and tlightTMain().
showFullWithInit()
uint8_t showFullWithInit (const Colors_t color, const uint8_t init)
Shows total stick with the same color if init is nonzero. Does nothing else.
Parameters
color Color code to fill
init Init mode. Function works if it's non zero only.
Returns
if nonzero the strip must be updated by sendDataToStrip
Definition at line 188 of file led_strip.c.
References showFull().
Referenced by allBlue(), allGreen(), allRed(), podnosGreen(), podnosRed(), and showOff().
Variable Documentation
Brightness
uint8_t Brightness = 0 static
The current brightness level.
Definition at line 18 of file led_strip.c.
Referenced by getBrightness(), and setBrightness().
colors
const Led_t colors[] static
Initial value:
=
{
        [BLACK]=            {0,   0,  0,  0 },
        [RED] =             {255, 0,  0,  0 },
        [GREEN]=            {0,   255,0,  0 },
        [BLUE]=             {0,   0,  255,0 },
        [WHITE]=            {0,   0,  0, 255},
        [YELLOW]=           {255, 255,0,  15},
        [MAGENTA]=          {255, 0,  255,20},
        [CYAN]=             {0, 255,  255,20},
        [DARK_RED]=         {50,  0,  0,  0 },
        [ORANGE]=           {100,50,  0,  0 },
        [REDDER]=           {200,50,  0,  0 },
        [GREEN10]=          {0,   26, 0,  0 },
        [BLUE10]=           {0,   0,  26, 0 }
}
Color names to values conversion.
Definition at line 32 of file led_strip.c.
Referenced by displayDigit(), putPixel(), and showFull().
leds
Led_t leds[NLEDS] static
Buffer for storing led pixel data.
Definition at line 53 of file led_strip.c.
Referenced by displayDigit(), putPixel(), sendDataToStrip(), and showFull().