PitStick: led_control.c File Reference
led_control.c File Reference
Contains led control logic for all modes:
#include <adc.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "buttons.h"
#include "rgbw.h"
#include "led_control.h"
#include "eeemu.h"
#include "clock.h"
#include "project_conf.h"
#include "prng.h"
#include "led_strip.h"
Data Structures
struct DispValue_t
In/out structure for configuring parameters.
struct V2Color_t
Voltage to color translation table element.
struct GreenStrip_t
struct Phase_desc_t
Phase description.
Macros
#define LA (90)
#define LB (720)
#define LB30 (5)
#define LB1_29 (LB - LB30)
#define LC (150)
#define LC1 (30)
Typedefs
typedef void(* pDispFunc_t) (const uint8_t value)
the is function type for displaying a value of the parameter that is changed in config mode
Enumerations
enum States_t {
STATE_IDLE = 0 , STATE_CONFIG , STATE_PIT , STATE_TLIGHT ,
STATE_PODNOS , STATE_SC , STATE_K2H , STATE_PITINVITE ,
STATE_IRONMAN , STATE_PIT2 , STATE_LOCK , STATE_CONFIG_PARAM_IDLE ,
STATE_CONFIG_PARAM_PRESSED , STATE_CONFIG_PARAM_RELEASED , STATE_CONFIG_PARAM_LONG_PRESSED , STATE_CONFIG_PARAM_SAVING ,
STATE_CONFIG_PARAM_NOT_SAVING , STATE_CONFIG_PARAM_WAITING , STATE_CONFIG_BEGIN , STATE_CONFIG_BRIGHTNESS ,
STATE_CONFIG_MODE , STATE_CONFIG_TSEQ , STATE_CONFIG_T1 , STATE_CONFIG_T2 ,
STATE_CONFIG_TLIGHT_MIN , STATE_CONFIG_TLIGHT_MAX , STATE_CONFIG_PODNOS_MODE , STATE_CONFIG_SC_END ,
STATE_CONFIG_K2H_END , STATE_CONFIG_IRONMAN_END , STATE_CONFIG_PIT2_END , STATE_CONFIG_PITINVITE_COLOR ,
STATE_CONFIG_END , STATE_LOCK_START , STATE_LOCK_ON , STATE_LOCK_OFF ,
STATE_GB_GREEN , STATE_GB_BLACK , STATE_TLIGHT_SLALOM , STATE_TLIGHT_SHOW_RANDOM ,
STATE_SC_SHOW_POWER , STATE_SC_MAIN
}
Main state machine states.
enum Working_Mode_t {
MODE_PIT = 0 , MODE_TLIGHT , MODE_PODNOS , MODE_SC ,
MODE_KART2H , MODE_PITINVITE , MODE_IRONMAN , MODE_PIT2 ,
MODE_TOTAL
}
Working modes. Pitstop or slalom tlight.
enum Config_idx_t {
CH_BRIGHTNESS = 0 , CH_MODE , CH_TSEQ , CH_T1 ,
CH_T2 , CH_TLIGHT_MIN , CH_TLIGHT_MAX , CH_PODNOS_MODE_TIME ,
CH_PITINVITE_COLOR
}
Flash storage config parameters.
enum EndMode_t { EM_CONTINUE = 0 , EM_CONTINUE_DO_NOT_UPDATE , EM_END_SAVING , EM_END_NOT_SAVING }
End of config param mode.
enum { TLIGHT_WORK_TIME = 5 , LAST_BLINK_TIME = 2 }
Functions
static void dispBrighnessPattern (void)
Show pattern for configuring brighness: red, green, blue and white strips.
static void displayBrightness (const uint8_t __attribute__((unused)) value)
Displays brightness setup pattern using the current brighness.
static void dispModePattern (const uint8_t value)
Displays mode pattern: green points for MODE_PIT and red strips for MODE_TLIGHT.
static void displayTSEQ (const uint8_t value)
static void displayT1 (const uint8_t value)
static void displayT2 (const uint8_t value)
static void displayTlightMin (const uint8_t value)
static void displayTlightMax (const uint8_t value)
static void displayPodnosModeTime (const uint8_t value)
static void displayPitInviteColor (const uint8_t value)
static void incValue (DispValue_t *const dV)
Incremens the value using min and max limits.
static uint8_t changeParam (DispValue_t *const dV, const uint8_t init)
show the param value and changes it during setup
static uint8_t config (uint8_t *const nextState)
all config mode processing is done here
static Colors_t getPowerColor (void)
Returns the color corresponding to current battery voltage. Battery needs to be charged immediately if red.
static uint8_t greenPhase (const uint8_t init)
Shows the first "green" phase of the pitstop mode.
static void dispYellowStrips (const uint8_t nstrips)
static uint8_t yellowPhase (const uint8_t init)
Yellow phase is 5-4-3-2-1-go phase for going out of pitlane. Starts at -T1-5s.
static uint8_t green2Black (const uint8_t init)
Green-to-black phase is phase after going out of pitlane. Geen light goes off after 2s and only 2 leds are displaying voltage. Starts at -T1.
static uint8_t redPre (const uint8_t init)
Red pre-phase is 2 red blinks at -T2. It's time when the driver must be at the intermediate point.
static void dispRedStrips (const uint8_t nstrips)
static void dispRedStripsReverse (const uint8_t nstrips)
static uint8_t tlight (const uint8_t init)
The main phase 5-4-3-2-1-go traffic light before crossing start/finish line. Starts at -5s and ends at 0.
static uint8_t tlightReverse (const uint8_t init)
The main phase 5-4-3-2-1-go traffic light before crossing start/finish line. Starts at -5s and ends at 0.
static uint8_t tlightForward (const uint8_t init)
static uint8_t lastGreenPhase (const uint8_t init)
Last phase : two green blinks starting from 0 (TSEQ)
static uint8_t processPhaseTable (const Phase_desc_t *const desc, uint8_t *const nextState, const uint32_t ms)
phase function processor. Calls needed phase function every time this function is called starting with
static uint8_t pitStopCalc (uint32_t const ms, uint8_t *const nextState)
Prepares and executes phase table for the pit stop mode.
static uint8_t yellowTPre (const uint8_t init)
tlight mode yellow pre-phase, two blinks at the start
static uint8_t tlightTMain (const uint8_t init)
Slalom traffic light. After the last strip goes on all light goes off at a random time interval.
static uint8_t showPower (const uint8_t init)
shows the current bat voltage
static uint8_t tlightMode (uint32_t const ms, uint8_t *const nextState)
fills and executes state table for the slalom traffic light
static uint8_t podnosRed (const uint8_t init)
Red phase of "Podnos" mode.
static uint8_t podnosGreen (const uint8_t init)
Green phase of "Podnos" mode.
static uint8_t podnosMode (uint32_t const ms, uint8_t *const nextState)
fills and executes state table for stop-and-go ("Podnos") mode.
static uint8_t show234 (const uint8_t init)
This is one of safety car script stages. It shows 2,3,4 lights using YELLOW color.
static uint8_t show1245 (const uint8_t init)
This is one of safety car script stages. It shows 1,2,4,5 lights using YELLOW color.
static uint8_t show15 (const uint8_t init)
This is one of safety car script stages. It shows 1,5 lights using YELLOW color.
static uint8_t showOff (const uint8_t init)
Turns led strip off.
static uint8_t scMode (uint32_t const ms)
Safety Car mode implementation. Safety Car mode is non-setupable endless mode. The sequence can be simply read from the desc variable.
static uint8_t darkPhase (const uint8_t _init)
static uint8_t allGreen (const uint8_t _init)
static uint8_t allGreenBlink (const uint8_t _init)
static uint8_t allRed (const uint8_t _init)
static uint8_t allRedBlink (const uint8_t _init)
static uint8_t allBlue (const uint8_t _init)
static void fill2PixelsWithFade (const Colors_t _bright, const Colors_t _dark, const uint8_t _bottom, const uint8_t _top)
static uint8_t oneByOneGreen (const uint8_t _init)
static uint8_t oneByOneBlue (const uint8_t _init)
static uint8_t k2hMode (uint32_t const ms, uint8_t *const nextState)
static uint8_t pitInviteMode (const uint32_t ms)
static uint8_t tlightPre (const uint8_t _init, const Colors_t _color)
static uint8_t tlightPreRed (const uint8_t _init)
static uint8_t tlightPreGreen (const uint8_t _init)
static uint8_t tlightPreBlue (const uint8_t _init)
static uint8_t ironB1_29 (const uint8_t _init)
IronMan phase B (race) subphases 1-29. Last phase will be interrupted by the scheduler and changed to ironB30.
static uint8_t ironB30row (const uint8_t _init, const uint8_t _row)
static uint8_t ironB30row0 (const uint8_t _init)
static uint8_t ironB30row1 (const uint8_t _init)
static uint8_t ironB30 (const uint8_t _init)
static uint8_t ironC1_10 (const uint8_t _init)
static uint8_t ironC11green (const uint8_t _init, const uint8_t _row)
static uint8_t ironC11green0 (const uint8_t _init)
static uint8_t ironC11green1 (const uint8_t _init)
static uint8_t ironC11 (const uint8_t _init)
static uint8_t ironmanMode (uint32_t const ms, uint8_t *const nextState)
static uint8_t pit2 (uint32_t const ms, uint8_t *const nextState)
static uint8_t lock (void)
Lock mode. Is shown at the end of all sequences (config, tlightMode, etc) to show that the stick is on and remind to switch it off.
void led_control (uint32_t const ms)
The entry point of the led control. Switches to pitstick, config mode or tlight.
Variables
static const uint16_t S = 1000u
static const uint32_t MIN = S * 60u
static const Colors_t num2color [] = {RED, GREEN, BLUE, ORANGE, YELLOW, WHITE}
static const uint32_t k2hOnMs = 200
static const uint32_t k2hOffMs = 800
static const uint32_t k2hOnDarkMs = 200
static const uint32_t k2hOffDarkMs = 4800
static const uint32_t k2hOnRedMs = 200
static const uint32_t k2hOffRedMs = 300
static const uint32_t greenPixelMs = 8 * S
static const uint32_t bluePixelMs = 10 * S
Detailed Description
Contains led control logic for all modes:
Pitstop
Traffic light for autoslalom
Rally stop-and-go ("Podnos") mode
Safety Car ("Zvyagin") mode
kart 2h mode
Pitstop invite mode
PitstopV2
Config mode
In config mode values are shown by displaying bars in different colors. One bar shows tens and other - ones.
For example if one (left) shows 2 leds and other (right) shows 9 leds it's 29. Colors are:
Orange : TSeq
Yellow : T1
Blue : T2
White : Tlight min
Green : Tlight max
Red : Podnos phase duration
Date
30-08-2021
Version
1.30
Definition in file led_control.c.
Macro Definition Documentation
LA
#define LA (90)
Definition at line 1734 of file led_control.c.
Referenced by ironmanMode().
LB
#define LB (720)
Definition at line 1735 of file led_control.c.
Referenced by ironmanMode().
LB1_29
#define LB1_29 (LB - LB30)
Definition at line 1737 of file led_control.c.
Referenced by ironmanMode().
LB30
#define LB30 (5)
Definition at line 1736 of file led_control.c.
LC
#define LC (150)
Definition at line 1739 of file led_control.c.
Referenced by ironmanMode().
LC1
#define LC1 (30)
Definition at line 1740 of file led_control.c.
Referenced by ironmanMode().
Typedef Documentation
pDispFunc_t
typedef void(* pDispFunc_t) (const uint8_t value)
the is function type for displaying a value of the parameter that is changed in config mode
Parameters
value - the value to display
Definition at line 140 of file led_control.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TLIGHT_WORK_TIME
Tlight working time. is used at yellow and tlight phases
LAST_BLINK_TIME
Time of the last green phase
Definition at line 1125 of file led_control.c.
Config_idx_t
enum Config_idx_t
Flash storage config parameters.
Enumerator
CH_BRIGHTNESS
Brightness
CH_MODE
Selected work mode
CH_TSEQ
Total pitstop time
CH_T1
T1 Time in seconds
CH_T2
T2 Time in seconds
CH_TLIGHT_MIN
Tlight random part minimal value in 1/10s
CH_TLIGHT_MAX
Tlight random part maximal value in 1/10s
CH_PODNOS_MODE_TIME
Stop-and-go mode time
CH_PITINVITE_COLOR
The color of pitlane invitation mode
Definition at line 112 of file led_control.c.
EndMode_t
enum EndMode_t
End of config param mode.
Enumerator
EM_CONTINUE
Param configuration is not complete but display must be updated
EM_CONTINUE_DO_NOT_UPDATE
Param configuration is not complete but display must not be updated
EM_END_SAVING
Param config mode is ended and parameter need to be saved
EM_END_NOT_SAVING
Parameter configuration mode is ended but parameter was not changed
Definition at line 128 of file led_control.c.
States_t
enum States_t
Main state machine states.
Enumerator
STATE_IDLE
Idle state. It's init state at which system can be for very short time
STATE_CONFIG
Config state. This state is entered if button is pressed at startup time
STATE_PIT
Main mode, pit stop
STATE_TLIGHT
Autoslalom mode. Switching between modes is done by the second config frame
STATE_PODNOS
Stop-and-go ("Podnos") mode
STATE_SC
Safety car mode
STATE_K2H
Karting 2H mode
STATE_PITINVITE
Pitlane invitation mode
STATE_IRONMAN
Ironman mode.
STATE_PIT2
Pitstop V2
STATE_LOCK
Lock mode. It works after ending one if the previous modes and is needed to remind that the stick is not turned off
STATE_CONFIG_PARAM_IDLE
Stick is in the configuration mode and mode processor is in the idle state
STATE_CONFIG_PARAM_PRESSED
Button is pressed while parameter is displayed
STATE_CONFIG_PARAM_RELEASED
Button is released while the parameter is displayed in configuration mode
STATE_CONFIG_PARAM_LONG_PRESSED
Button is long pressed while parameter is displayed
STATE_CONFIG_PARAM_SAVING
Current parameter was changed and will be saved. Short red blink indicates that.
STATE_CONFIG_PARAM_NOT_SAVING
Current parameter was not changed and will not be saved. Short turn the stick off confirms that
STATE_CONFIG_PARAM_WAITING
Waiting after last button press
STATE_CONFIG_BEGIN
Beginning of the configuration process
STATE_CONFIG_BRIGHTNESS
Configuring brightness
STATE_CONFIG_MODE
Configuring mode (tlight for slalom or pitstick mode)
STATE_CONFIG_TSEQ
Configuring total pitstop duration
STATE_CONFIG_T1
Configuring T1. T1 is the time kart starts going from the pitlane
STATE_CONFIG_T2
Configuring T1. T2 is time from intermediate point and crossing start/stop line
STATE_CONFIG_TLIGHT_MIN
Configuring minimal time for the last phase in tlingt mode. 1/10s resolution
STATE_CONFIG_TLIGHT_MAX
Configuring maximal time for the last phase in tlingt mode. 1/10s resolution
STATE_CONFIG_PODNOS_MODE
Set stop-and-go mode duration
STATE_CONFIG_SC_END
End of safety car mode config
STATE_CONFIG_K2H_END
End of Kartig 2h mode config
STATE_CONFIG_IRONMAN_END
End of IronMan mode config
STATE_CONFIG_PIT2_END
End of Pit v2 mode config
STATE_CONFIG_PITINVITE_COLOR
Pit line invitation config mode
STATE_CONFIG_END
End of configuration process
STATE_LOCK_START
Start lock mode. Lock mode is turned on after all operations are complete to remimd switchig the stick off
STATE_LOCK_ON
Lock mode. Red light+battery power is on
STATE_LOCK_OFF
Lock mode. All lights are off
STATE_GB_GREEN
Green->black phase. Green leds are on
STATE_GB_BLACK
Green->black phase. All is off
STATE_TLIGHT_SLALOM
Slalom mode start
STATE_TLIGHT_SHOW_RANDOM
Random pause after the fifth strip is on
STATE_SC_SHOW_POWER
First phase of Safety Car mode, showing battery level
STATE_SC_MAIN
Main phase of safety car mode
Definition at line 47 of file led_control.c.
Working_Mode_t
enum Working_Mode_t
Working modes. Pitstop or slalom tlight.
Enumerator
MODE_PIT
Pitstop mode
MODE_TLIGHT
Slalom traffic light mode
MODE_PODNOS
Mode for rally stop-and-go
MODE_SC
Safety car mode
MODE_KART2H
Karting 2h mode
MODE_PITINVITE
Pitlane invitation mode
MODE_IRONMAN
Iron man mode. Tlight + pit
MODE_PIT2
Pitstop V2, DD08012025
MODE_TOTAL
Total number of modes
Definition at line 96 of file led_control.c.
Function Documentation
allBlue()
static uint8_t allBlue (const uint8_t _init) static
Definition at line 1510 of file led_control.c.
References BLUE, and showFullWithInit().
Referenced by pit2().
allGreen()
static uint8_t allGreen (const uint8_t _init) static
Definition at line 1475 of file led_control.c.
References GREEN, and showFullWithInit().
Referenced by allGreenBlink(), and pit2().
allGreenBlink()
static uint8_t allGreenBlink (const uint8_t _init) static
Definition at line 1480 of file led_control.c.
References allGreen(), blink(), k2hOffMs, k2hOnMs, and showOff().
Referenced by k2hMode().
allRed()
static uint8_t allRed (const uint8_t _init) static
Definition at line 1493 of file led_control.c.
References RED, and showFullWithInit().
Referenced by allRedBlink(), and pit2().
allRedBlink()
static uint8_t allRedBlink (const uint8_t _init) static
Definition at line 1498 of file led_control.c.
References allRed(), blink(), k2hOffRedMs, k2hOnRedMs, and showOff().
Referenced by k2hMode().
changeParam()
static uint8_t changeParam (DispValue_t *const dV, const uint8_t init) static
show the param value and changes it during setup
Parameters
dV value and limits
init This param is zero if it's not first call
Returns
0 if sending buffer to strip is not needed
Definition at line 306 of file led_control.c.
References B_CONFIG, BLACK, DARK_RED, DispValue_t::dispFunc, EM_CONTINUE, EM_CONTINUE_DO_NOT_UPDATE, EM_END_NOT_SAVING, EM_END_SAVING, DispValue_t::endMode, incValue(), IsExpiredTimer(), IsLongPressed(), IsPressed(), DispValue_t::max, DispValue_t::min, put2pixels(), ResetTimer(), showFull(), STATE_CONFIG_PARAM_IDLE, STATE_CONFIG_PARAM_LONG_PRESSED, STATE_CONFIG_PARAM_NOT_SAVING, STATE_CONFIG_PARAM_PRESSED, STATE_CONFIG_PARAM_RELEASED, STATE_CONFIG_PARAM_SAVING, STATE_CONFIG_PARAM_WAITING, and DispValue_t::value.
Referenced by config().
config()
static uint8_t config (uint8_t *const nextState) static
all config mode processing is done here
Parameters
nextState pointer to the result. Non zero value shows that configuration is done and you can pass to the next step
Returns
nonzero value shows that data is updated and must be sent to the strip
Definition at line 434 of file led_control.c.
References BLACK, CH_BRIGHTNESS, CH_MODE, CH_PITINVITE_COLOR, CH_PODNOS_MODE_TIME, CH_T1, CH_T2, CH_TLIGHT_MAX, CH_TLIGHT_MIN, CH_TSEQ, changeParam(), dispBrighnessPattern(), DispValue_t::dispFunc, displayBrightness(), displayPitInviteColor(), displayPodnosModeTime(), displayT1(), displayT2(), displayTlightMax(), displayTlightMin(), displayTSEQ(), dispModePattern(), eeemu_write(), eeemuGetValue(), EM_CONTINUE, EM_CONTINUE_DO_NOT_UPDATE, EM_END_SAVING, DispValue_t::endMode, DispValue_t::max, MAX_BRIGHNESS_LEVELS, MAX_STORED, DispValue_t::min, MODE_IRONMAN, MODE_KART2H, MODE_PIT, MODE_PIT2, MODE_PITINVITE, MODE_PODNOS, MODE_SC, MODE_TLIGHT, MODE_TOTAL, NLEDS, num2color, PODNOS_MODE_MAX, PODNOS_MODE_MIN, put2pixels(), RED, ResetTimer(), setBrightness(), showFull(), STATE_CONFIG_BEGIN, STATE_CONFIG_BRIGHTNESS, STATE_CONFIG_END, STATE_CONFIG_IRONMAN_END, STATE_CONFIG_K2H_END, STATE_CONFIG_MODE, STATE_CONFIG_PIT2_END, STATE_CONFIG_PITINVITE_COLOR, STATE_CONFIG_PODNOS_MODE, STATE_CONFIG_SC_END, STATE_CONFIG_T1, STATE_CONFIG_T2, STATE_CONFIG_TLIGHT_MAX, STATE_CONFIG_TLIGHT_MIN, STATE_CONFIG_TSEQ, T1MIN, T1MIN2, T2MIN, T2MIN2, TLIGHT_MAX, TLIGHT_MIN, TSEQ_MAX, TSEQ_MIN, and DispValue_t::value.
Referenced by led_control().
darkPhase()
static uint8_t darkPhase (const uint8_t _init) static
Definition at line 1463 of file led_control.c.
References blink(), k2hOffDarkMs, k2hOnDarkMs, showOff(), and showPower().
Referenced by ironmanMode(), and k2hMode().
dispBrighnessPattern()
static void dispBrighnessPattern (void) static
Show pattern for configuring brighness: red, green, blue and white strips.
Definition at line 159 of file led_control.c.
References BLACK, BLUE, GREEN, put2pixels(), RED, showFull(), and WHITE.
Referenced by config(), and displayBrightness().
displayBrightness()
static void displayBrightness (const uint8_t __attribute__((unused)) value) static
Displays brightness setup pattern using the current brighness.
Parameters
value brightness value
Definition at line 175 of file led_control.c.
References dispBrighnessPattern().
Referenced by config().
displayPitInviteColor()
static void displayPitInviteColor (const uint8_t value) static
Definition at line 278 of file led_control.c.
References BLACK, dispStrip(), num2color, and showFull().
Referenced by config().
displayPodnosModeTime()
static void displayPodnosModeTime (const uint8_t value) static
Definition at line 273 of file led_control.c.
References displayNumber(), and RED.
Referenced by config().
displayT1()
static void displayT1 (const uint8_t value) static
Definition at line 253 of file led_control.c.
References displayNumber(), and YELLOW.
Referenced by config().
displayT2()
static void displayT2 (const uint8_t value) static
Definition at line 258 of file led_control.c.
References BLUE, and displayNumber().
Referenced by config().
displayTlightMax()
static void displayTlightMax (const uint8_t value) static
Definition at line 268 of file led_control.c.
References displayNumber(), and GREEN.
Referenced by config().
displayTlightMin()
static void displayTlightMin (const uint8_t value) static
Definition at line 263 of file led_control.c.
References displayNumber(), and WHITE.
Referenced by config().
displayTSEQ()
static void displayTSEQ (const uint8_t value) static
Definition at line 248 of file led_control.c.
References displayNumber(), and ORANGE.
Referenced by config().
dispModePattern()
static void dispModePattern (const uint8_t value) static
Displays mode pattern: green points for MODE_PIT and red strips for MODE_TLIGHT.
Parameters
value selected mode
Definition at line 184 of file led_control.c.
References BLACK, BLUE, GREEN, MODE_IRONMAN, MODE_KART2H, MODE_PIT, MODE_PIT2, MODE_PITINVITE, MODE_PODNOS, MODE_SC, MODE_TLIGHT, put2pixels(), putPixel(), RED, showFull(), and YELLOW.
Referenced by config().
dispRedStrips()
static void dispRedStrips (const uint8_t nstrips) static
Definition at line 975 of file led_control.c.
References dispStrips(), and RED.
Referenced by tlight(), tlightReverse(), and tlightTMain().
dispRedStripsReverse()
static void dispRedStripsReverse (const uint8_t nstrips) static
Definition at line 980 of file led_control.c.
References dispStripsRevese(), and RED.
Referenced by tlightForward().
dispYellowStrips()
static void dispYellowStrips (const uint8_t nstrips) static
Definition at line 884 of file led_control.c.
References dispStrips(), and YELLOW.
Referenced by yellowPhase().
fill2PixelsWithFade()
static void fill2PixelsWithFade (const Colors_t _bright, const Colors_t _dark, const uint8_t _bottom, const uint8_t _top) static
Definition at line 1515 of file led_control.c.
References fill2Pixels(), and put2pixels().
Referenced by oneByOneBlue(), and oneByOneGreen().
getPowerColor()
static Colors_t getPowerColor (void) static
Returns the color corresponding to current battery voltage. Battery needs to be charged immediately if red.
Returns
Color index
Definition at line 786 of file led_control.c.
References V2Color_t::color, GetAdc_Voltage(), GREEN, ORANGE, RED, REDDER, and YELLOW.
Referenced by blinkTwice(), green2Black(), greenPhase(), lastGreenPhase(), lock(), pitInviteMode(), redPre(), showPower(), and yellowTPre().
green2Black()
static uint8_t green2Black (const uint8_t init) static
Green-to-black phase is phase after going out of pitlane. Geen light goes off after 2s and only 2 leds are displaying voltage. Starts at -T1.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 921 of file led_control.c.
References BLACK, getPowerColor(), GREEN, IsExpiredTimer(), put2pixels(), ResetTimer(), showFull(), STATE_GB_BLACK, and STATE_GB_GREEN.
Referenced by pitStopCalc().
greenPhase()
static uint8_t greenPhase (const uint8_t init) static
Shows the first "green" phase of the pitstop mode.
Parameters
init is non zero if this is first call
Returns
nonzero value if data is changed and update needed Green phase shows 5 strips blinking at 1Hz. Each 20secons one strip turns off. So at nineteenth second 5 strips are blinking, at 21 - four strips. At 41 3 strips are blinking.
Definition at line 832 of file led_control.c.
References BLACK, getPowerColor(), GREEN, IsExpiredTimer(), GreenStrip_t::number, put2pixels(), ResetTimer(), and showFull().
Referenced by pitStopCalc().
incValue()
static void incValue (DispValue_t *const dV) static
Incremens the value using min and max limits.
Parameters
dV
Definition at line 291 of file led_control.c.
References DispValue_t::max, DispValue_t::min, and DispValue_t::value.
Referenced by changeParam().
ironB1_29()
static uint8_t ironB1_29 (const uint8_t _init) static
IronMan phase B (race) subphases 1-29. Last phase will be interrupted by the scheduler and changed to ironB30.
Parameters
_init !0 if it's first run
Returns
!0 if led strip must be updated
Definition at line 1793 of file led_control.c.
References BLACK, IsExpiredTimer(), put2pixels(), RED, ResetTimer(), S, and showFull().
Referenced by ironmanMode().
ironB30()
static uint8_t ironB30 (const uint8_t _init) static
Definition at line 1862 of file led_control.c.
References blink(), ironB30row0(), ironB30row1(), and S.
Referenced by ironmanMode().
ironB30row()
static uint8_t ironB30row (const uint8_t _init, const uint8_t _row) static
Definition at line 1834 of file led_control.c.
References BLACK, putPixel(), RED, and showFull().
Referenced by ironB30row0(), and ironB30row1().
ironB30row0()
static uint8_t ironB30row0 (const uint8_t _init) static
Definition at line 1851 of file led_control.c.
References ironB30row().
Referenced by ironB30().
ironB30row1()
static uint8_t ironB30row1 (const uint8_t _init) static
Definition at line 1856 of file led_control.c.
References ironB30row().
Referenced by ironB30().
ironC11()
static uint8_t ironC11 (const uint8_t _init) static
Definition at line 1944 of file led_control.c.
References blink(), ironC11green0(), ironC11green1(), and S.
Referenced by ironmanMode().
ironC11green()
static uint8_t ironC11green (const uint8_t _init, const uint8_t _row) static
Definition at line 1917 of file led_control.c.
References BLACK, GREEN, putPixel(), and showFull().
Referenced by ironC11green0(), and ironC11green1().
ironC11green0()
static uint8_t ironC11green0 (const uint8_t _init) static
Definition at line 1933 of file led_control.c.
References ironC11green().
Referenced by ironC11().
ironC11green1()
static uint8_t ironC11green1 (const uint8_t _init) static
Definition at line 1938 of file led_control.c.
References ironC11green().
Referenced by ironC11().
ironC1_10()
static uint8_t ironC1_10 (const uint8_t _init) static
Definition at line 1873 of file led_control.c.
References BLACK, GREEN, IsExpiredTimer(), put2pixels(), ResetTimer(), S, and showFull().
Referenced by ironmanMode().
ironmanMode()
static uint8_t ironmanMode (uint32_t const ms, uint8_t *const nextState) static
Definition at line 1957 of file led_control.c.
References darkPhase(), genRandom(), ironB1_29(), ironB30(), ironC11(), ironC1_10(), LA, LB, LB1_29, LC, LC1, processPhaseTable(), S, showOff(), Phase_desc_t::start, tlightPreRed(), and tlightReverse().
Referenced by led_control().
k2hMode()
static uint8_t k2hMode (uint32_t const ms, uint8_t *const nextState) static
Definition at line 1658 of file led_control.c.
References allGreenBlink(), allRedBlink(), darkPhase(), MIN, oneByOneBlue(), oneByOneGreen(), processPhaseTable(), and S.
Referenced by led_control().
lastGreenPhase()
static uint8_t lastGreenPhase (const uint8_t init) static
Last phase : two green blinks starting from 0 (TSEQ)
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1069 of file led_control.c.
References blinkTwice(), getPowerColor(), and GREEN.
Referenced by pitStopCalc().
led_control()
void led_control (uint32_t const ms)
The entry point of the led control. Switches to pitstick, config mode or tlight.
function that prepares led strip out data at every step (100ms)
Parameters
ms milliseconds from the start
Definition at line 2102 of file led_control.c.
References B_CONFIG, CH_BRIGHTNESS, CH_MODE, config(), eeemuGetValue(), ironmanMode(), IsPressed(), k2hMode(), lock(), MODE_IRONMAN, MODE_KART2H, MODE_PIT, MODE_PIT2, MODE_PITINVITE, MODE_PODNOS, MODE_SC, MODE_TLIGHT, pit2(), pitInviteMode(), pitStopCalc(), podnosMode(), scMode(), sendDataToStrip(), setBrightness(), STATE_CONFIG, STATE_IDLE, STATE_IRONMAN, STATE_K2H, STATE_LOCK, STATE_PIT, STATE_PIT2, STATE_PITINVITE, STATE_PODNOS, STATE_SC, STATE_TLIGHT, and tlightMode().
Referenced by ledControl_wrapper().
lock()
static uint8_t lock (void) static
Lock mode. Is shown at the end of all sequences (config, tlightMode, etc) to show that the stick is on and remind to switch it off.
Returns
nonzero means the led strip must be updated
Definition at line 2051 of file led_control.c.
References BLACK, CH_BRIGHTNESS, DARK_RED, eeemuGetValue(), getPowerColor(), IsExpiredTimer(), NLEDS, put2pixels(), ResetTimer(), setBrightness(), showFull(), STATE_LOCK_OFF, STATE_LOCK_ON, and STATE_LOCK_START.
Referenced by led_control().
oneByOneBlue()
static uint8_t oneByOneBlue (const uint8_t _init) static
Definition at line 1597 of file led_control.c.
References BLACK, BLUE, BLUE10, bluePixelMs, fill2PixelsWithFade(), IsExpiredTimer(), k2hOffMs, k2hOnMs, NLEDS, put2pixels(), RED, ResetTimer(), and showFull().
Referenced by k2hMode().
oneByOneGreen()
static uint8_t oneByOneGreen (const uint8_t _init) static
Definition at line 1535 of file led_control.c.
References BLACK, BLUE, fill2PixelsWithFade(), GREEN, GREEN10, greenPixelMs, IsExpiredTimer(), k2hOffMs, k2hOnMs, NLEDS, put2pixels(), ResetTimer(), and showFull().
Referenced by k2hMode().
pit2()
static uint8_t pit2 (uint32_t const ms, uint8_t *const nextState) static
Definition at line 2008 of file led_control.c.
References allBlue(), allGreen(), allRed(), genRandom(), processPhaseTable(), S, showOff(), Phase_desc_t::start, tlightForward(), tlightPreBlue(), tlightPreGreen(), and tlightPreRed().
Referenced by led_control().
pitInviteMode()
static uint8_t pitInviteMode (const uint32_t ms) static
Definition at line 1698 of file led_control.c.
References BLACK, CH_PITINVITE_COLOR, dispStrip(), eeemuGetValue(), getPowerColor(), num2color, put2pixels(), and showFull().
Referenced by led_control().
pitStopCalc()
static uint8_t pitStopCalc (uint32_t const ms, uint8_t *const nextState) static
Prepares and executes phase table for the pit stop mode.
Parameters
[in] ms millisecons from the start
[out] nextState out parameter. Becomes nonzero when all table is processed
Returns
nonzero means the led strip must be updated
Definition at line 1136 of file led_control.c.
References CH_T1, CH_T2, CH_TSEQ, eeemuGetValue(), green2Black(), greenPhase(), LAST_BLINK_TIME, lastGreenPhase(), processPhaseTable(), redPre(), S, tlight(), TLIGHT_WORK_TIME, and yellowPhase().
Referenced by led_control().
podnosGreen()
static uint8_t podnosGreen (const uint8_t init) static
Green phase of "Podnos" mode.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1284 of file led_control.c.
References GREEN, and showFullWithInit().
Referenced by podnosMode().
podnosMode()
static uint8_t podnosMode (uint32_t const ms, uint8_t *const nextState) static
fills and executes state table for stop-and-go ("Podnos") mode.
Parameters
ms milliseconds from the start
nextState out param. Is non-zero if sequence is finished and we need to go to the next (lock) state
Returns
nonzero means the led strip must be updated
Definition at line 1297 of file led_control.c.
References CH_PODNOS_MODE_TIME, eeemuGetValue(), podnosGreen(), podnosRed(), processPhaseTable(), S, and showPower().
Referenced by led_control().
podnosRed()
static uint8_t podnosRed (const uint8_t init) static
Red phase of "Podnos" mode.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1273 of file led_control.c.
References RED, and showFullWithInit().
Referenced by podnosMode().
processPhaseTable()
static uint8_t processPhaseTable (const Phase_desc_t *const desc, uint8_t *const nextState, const uint32_t ms) static
phase function processor. Calls needed phase function every time this function is called starting with
Phase_desc_t::start field of it's descriptor.
Parameters
desc Descriptor table
nextState out parameter. Becomes nonzero when all table is processed
ms millisecons from the start
Returns
nonzero means the led strip must be updated
Definition at line 1092 of file led_control.c.
References Phase_desc_t::pPhase.
Referenced by ironmanMode(), k2hMode(), pit2(), pitStopCalc(), podnosMode(), scMode(), and tlightMode().
redPre()
static uint8_t redPre (const uint8_t init) static
Red pre-phase is 2 red blinks at -T2. It's time when the driver must be at the intermediate point.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 970 of file led_control.c.
References blinkTwice(), getPowerColor(), and RED.
Referenced by pitStopCalc().
scMode()
static uint8_t scMode (uint32_t const ms) static
Safety Car mode implementation. Safety Car mode is non-setupable endless mode. The sequence can be simply read from the desc variable.
Parameters
[in] ms milliseconds for start
Returns
nonzero if led strip must be updated
Definition at line 1395 of file led_control.c.
References IsExpiredTimer(), processPhaseTable(), ResetTimer(), S, show1245(), show15(), show234(), showOff(), showPower(), STATE_IDLE, STATE_SC_MAIN, and STATE_SC_SHOW_POWER.
Referenced by led_control().
show1245()
static uint8_t show1245 (const uint8_t init) static
This is one of safety car script stages. It shows 1,2,4,5 lights using YELLOW color.
Parameters
init is nonzero at the first run
Returns
nonzero if led strip must be updated
Definition at line 1340 of file led_control.c.
References BLACK, dispStrip(), showFull(), and YELLOW.
Referenced by scMode().
show15()
static uint8_t show15 (const uint8_t init) static
This is one of safety car script stages. It shows 1,5 lights using YELLOW color.
Parameters
init is nonzero at the first run
Returns
nonzero if led strip must be updated
Definition at line 1362 of file led_control.c.
References BLACK, dispStrip(), showFull(), and YELLOW.
Referenced by scMode().
show234()
static uint8_t show234 (const uint8_t init) static
This is one of safety car script stages. It shows 2,3,4 lights using YELLOW color.
Parameters
init is nonzero at the first run
Returns
nonzero if led strip must be updated
Definition at line 1319 of file led_control.c.
References BLACK, dispStrip(), showFull(), and YELLOW.
Referenced by scMode().
showOff()
static uint8_t showOff (const uint8_t init) static
Turns led strip off.
Parameters
init is nonzero at the first run
Returns
nonzero if led strip must be updated
Definition at line 1383 of file led_control.c.
References BLACK, and showFullWithInit().
Referenced by allGreenBlink(), allRedBlink(), darkPhase(), ironmanMode(), pit2(), and scMode().
showPower()
static uint8_t showPower (const uint8_t init) static
shows the current bat voltage
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1233 of file led_control.c.
References BLACK, getPowerColor(), put2pixels(), and showFull().
Referenced by darkPhase(), podnosMode(), scMode(), and tlightMode().
tlight()
static uint8_t tlight (const uint8_t init) static
The main phase 5-4-3-2-1-go traffic light before crossing start/finish line. Starts at -5s and ends at 0.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 991 of file led_control.c.
References dispRedStrips(), IsExpiredTimer(), and ResetTimer().
Referenced by pitStopCalc().
tlightForward()
static uint8_t tlightForward (const uint8_t init) static
Definition at line 1041 of file led_control.c.
References dispRedStripsReverse(), IsExpiredTimer(), and ResetTimer().
Referenced by pit2().
tlightMode()
static uint8_t tlightMode (uint32_t const ms, uint8_t *const nextState) static
fills and executes state table for the slalom traffic light
Parameters
ms milliseconds from the start
nextState out param. Is non-zero if sequence is finished and we need to go to the next (lock) state
Returns
nonzero means the led strip must be updated
Definition at line 1252 of file led_control.c.
References CH_TLIGHT_MAX, eeemuGetValue(), processPhaseTable(), S, showPower(), tlightTMain(), and yellowTPre().
Referenced by led_control().
tlightPre()
static uint8_t tlightPre (const uint8_t _init, const Colors_t _color) static
Definition at line 1741 of file led_control.c.
References BLACK, fill2Pixels(), IsExpiredTimer(), ResetTimer(), and showFull().
Referenced by tlightPreBlue(), tlightPreGreen(), and tlightPreRed().
tlightPreBlue()
static uint8_t tlightPreBlue (const uint8_t _init) static
Definition at line 1783 of file led_control.c.
References BLUE, and tlightPre().
Referenced by pit2().
tlightPreGreen()
static uint8_t tlightPreGreen (const uint8_t _init) static
Definition at line 1778 of file led_control.c.
References GREEN, and tlightPre().
Referenced by pit2().
tlightPreRed()
static uint8_t tlightPreRed (const uint8_t _init) static
Definition at line 1773 of file led_control.c.
References RED, and tlightPre().
Referenced by ironmanMode(), and pit2().
tlightReverse()
static uint8_t tlightReverse (const uint8_t init) static
The main phase 5-4-3-2-1-go traffic light before crossing start/finish line. Starts at -5s and ends at 0.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1019 of file led_control.c.
References dispRedStrips(), IsExpiredTimer(), and ResetTimer().
Referenced by ironmanMode().
tlightTMain()
static uint8_t tlightTMain (const uint8_t init) static
Slalom traffic light. After the last strip goes on all light goes off at a random time interval.
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1178 of file led_control.c.
References BLACK, CH_TLIGHT_MAX, CH_TLIGHT_MIN, dispRedStrips(), eeemuGetValue(), genRandom(), IsExpiredTimer(), ResetTimer(), showFull(), STATE_TLIGHT_SHOW_RANDOM, and STATE_TLIGHT_SLALOM.
Referenced by tlightMode().
yellowPhase()
static uint8_t yellowPhase (const uint8_t init) static
Yellow phase is 5-4-3-2-1-go phase for going out of pitlane. Starts at -T1-5s.
Parameters
init is nonzero if it's first run
Returns
nonzero means the led strip must be updated
Definition at line 893 of file led_control.c.
References dispYellowStrips(), IsExpiredTimer(), and ResetTimer().
Referenced by pitStopCalc().
yellowTPre()
static uint8_t yellowTPre (const uint8_t init) static
tlight mode yellow pre-phase, two blinks at the start
Parameters
init is nonzero at the first run
Returns
nonzero means the led strip must be updated
Definition at line 1168 of file led_control.c.
References blinkTwice(), getPowerColor(), and YELLOW.
Referenced by tlightMode().
Variable Documentation
bluePixelMs
const uint32_t bluePixelMs = 10 * S static
Definition at line 1460 of file led_control.c.
Referenced by oneByOneBlue().
greenPixelMs
const uint32_t greenPixelMs = 8 * S static
Definition at line 1459 of file led_control.c.
Referenced by oneByOneGreen().
k2hOffDarkMs
const uint32_t k2hOffDarkMs = 4800 static
Definition at line 1456 of file led_control.c.
Referenced by darkPhase().
k2hOffMs
const uint32_t k2hOffMs = 800 static
Definition at line 1454 of file led_control.c.
Referenced by allGreenBlink(), oneByOneBlue(), and oneByOneGreen().
k2hOffRedMs
const uint32_t k2hOffRedMs = 300 static
Definition at line 1458 of file led_control.c.
Referenced by allRedBlink().
k2hOnDarkMs
const uint32_t k2hOnDarkMs = 200 static
Definition at line 1455 of file led_control.c.
Referenced by darkPhase().
k2hOnMs
const uint32_t k2hOnMs = 200 static
Definition at line 1453 of file led_control.c.
Referenced by allGreenBlink(), oneByOneBlue(), and oneByOneGreen().
k2hOnRedMs
const uint32_t k2hOnRedMs = 200 static
Definition at line 1457 of file led_control.c.
Referenced by allRedBlink().
MIN
const uint32_t MIN = S * 60u static
milliseconds per minute
Definition at line 42 of file led_control.c.
Referenced by k2hMode().
num2color
const Colors_t num2color[] = {RED, GREEN, BLUE, ORANGE, YELLOW, WHITE} static
Definition at line 154 of file led_control.c.
Referenced by config(), displayPitInviteColor(), and pitInviteMode().
S
const uint16_t S = 1000u static
millisecons per second
Definition at line 41 of file led_control.c.
Referenced by ironB1_29(), ironB30(), ironC11(), ironC1_10(), ironmanMode(), k2hMode(), pit2(), pitStopCalc(), podnosMode(), scMode(), and tlightMode().