PitStick: led_control.h File Reference
led_control.h File Reference
Contains function that controls led strip.
#include <stdint.h>
Functions
void led_control (uint32_t const ms)
function that prepares led strip out data at every step (100ms)
Detailed Description
Contains function that controls led strip.
Date
7-11-2020
Definition in file led_control.h.
Function Documentation
led_control()
void led_control (uint32_t const ms)
function that prepares led strip out data at every step (100ms)
Parameters
ms - number of milliseconds that had passed after pitstick is on
function that prepares led strip out data at every step (100ms)
Parameters
ms milliseconds from the start
Definition at line 1344 of file led_control.c.
References B_CONFIG, CH_BRIGHTNESS, CH_MODE, config(), eeemuGetValue(), IsPressed(), lock(), MODE_PIT, MODE_PODNOS, MODE_SC, MODE_TLIGHT, pitStopCalc(), podnosMode(), scMode(), sendDataToStrip(), setBrightness(), STATE_CONFIG, STATE_IDLE, STATE_LOCK, STATE_PIT, STATE_PODNOS, STATE_SC, STATE_TLIGHT, and tlightMode().
Referenced by ledControl_wrapper().