PitStick: main.c File Reference
main.c File Reference
The file contains upper level init functions calls and main while(1) cycle.
#include "bll.h"
#include "clock.h"
#include "gpio.h"
#include "stm32f1xx.h"
#include "timer_dma.h"
#include "buttons.h"
#include "eeemu.h"
#include "watchdog.h"
#include "adc.h"
Functions
static void Init (void)
Contains all init functions.
void main (void)
Detailed Description
The file contains upper level init functions calls and main while(1) cycle.
Version
1.20
Date
12-12-2019
Definition in file main.c.
Function Documentation
Init()
static void Init (void) static
Contains all init functions.
Definition at line 119 of file main.c.
References Adc_Init(), Buttons_Init(), Clock_HSE_Init(), eeemu_Init(), Gpio_Init(), Systick_Init(), tim2_Init(), and watchdog_Init().
Referenced by main().
main()
void main (void)
Definition at line 132 of file main.c.
References Init(), MainLoop_Iteration(), and Reset_Watchdog().