PitStick: prng.c File Reference
prng.c File Reference
contains function for generation pseudo-rundonm number sequence for slalom light. x[n+1] = (a*x[n] + b) mod m is used
#include "prng.h"
#include "eeemu.h"
#include "adc.h"
Enumerations
enum { a = 5 , b = 17 }
Functions
uint16_t genRandom (const uint16_t min, const uint16_t max)
gets the next random value of the sequence
Detailed Description
contains function for generation pseudo-rundonm number sequence for slalom light. x[n+1] = (a*x[n] + b) mod m is used
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
17-11-2019
Definition in file prng.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
a
a param from the formula
b
b param from the formula
Definition at line 11 of file prng.c.
Function Documentation
genRandom()
uint16_t genRandom (const uint16_t min, const uint16_t max)
gets the next random value of the sequence
Generates a pseudo-random number in range [min..max] Result is stored in the flash to be used next time.
Parameters
min minimal value
max maximal value
Returns
pseudorandom number
Definition at line 23 of file prng.c.
References a, b, eeemuSeedGet(), eeemuSeedSet(), and getEntropy().
Referenced by ironmanMode(), pit2(), and tlightTMain().