PitStick: prng.h File Reference
prng.h File Reference
Contains prototypes of function that returns random value between min and max. Caculated value is stored in flash to be used as initial one next time.
#include <stdint.h>
Functions
uint16_t genRandom (const uint16_t min, const uint16_t max)
Generates a pseudo-random number in range [min..max] Result is stored in the flash to be used next time.
Detailed Description
Contains prototypes of function that returns random value between min and max. Caculated value is stored in flash to be used as initial one next time.
Definition in file prng.h.
Function Documentation
genRandom()
uint16_t genRandom (const uint16_t min, const uint16_t max)
Generates a pseudo-random number in range [min..max] Result is stored in the flash to be used next time.
Parameters
min minimal value of the generated random
max maximal value of the generated random number
Returns
random number.
Generates a pseudo-random number in range [min..max] Result is stored in the flash to be used next time.
Parameters
min minimal value
max maximal value
Returns
pseudorandom number
Definition at line 23 of file prng.c.
References a, b, eeemuSeedGet(), eeemuSeedSet(), and getEntropy().
Referenced by tlightTMain().