PitStick: rgbw.h File Reference
rgbw.h File Reference
Contains prototypes and data types for SK6812 led strip driver.
#include <stdint.h>
Data Structures
struct Led_t
Struct defining color for each led.
Functions
void displayStrip (Led_t *const Leds)
Sends data to the strip. Number of leds is NLEDS.
Detailed Description
Contains prototypes and data types for SK6812 led strip driver.
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
21-11-2019
Version
1.00
Definition in file rgbw.h.
Function Documentation
displayStrip()
void displayStrip (Led_t *const Leds)
Sends data to the strip. Number of leds is NLEDS.
Parameters
Leds Pointer to the array of led data
Definition at line 85 of file rgbw.c.
References BitData, ConvertLeds(), tim2_set_data(), and tim2_TransferBits().
Referenced by sendDataToStrip().