PitStick: rgbw.c File Reference
rgbw.c File Reference
Contains SK6812 led strip driver implementation. The driver converts rgbw led data to serial array of short and long PWM pulses that are sent by dma to timer2 and use it's ch1 out.
#include "rgbw.h"
#include "timer_dma.h"
#include "led_control.h"
#include "led_strip.h"
#include "project_conf.h"
Macros
#define CCR_0 20 /* 0.5us */
#define CCR_1 64 /* 1.2us */
#define RESET_BITS 40
Functions
static void ConvertLeds (Led_t *const Leds)
Converts leds array to serial bit array.
void displayStrip (Led_t *const Leds)
Sends data to the strip. Number of leds is NLEDS.
Variables
static uint8_t BitData [NLEDS *8 *4+RESET_BITS+1]
Led array bits. Contains one byte for bit so each led takes 32bytes. Also RESET_BITS are added and one byte to switch the out off.
Detailed Description
Contains SK6812 led strip driver implementation. The driver converts rgbw led data to serial array of short and long PWM pulses that are sent by dma to timer2 and use it's ch1 out.
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
21-11-2019
Version
1.00
Definition in file rgbw.c.
Macro Definition Documentation
CCR_0
#define CCR_0 20 /* 0.5us */
Definition at line 17 of file rgbw.c.
Referenced by ConvertLeds().
CCR_1
#define CCR_1 64 /* 1.2us */
Definition at line 18 of file rgbw.c.
Referenced by ConvertLeds().
RESET_BITS
#define RESET_BITS 40
Definition at line 19 of file rgbw.c.
Referenced by ConvertLeds().
Function Documentation
ConvertLeds()
static void ConvertLeds (Led_t *const Leds) static
Converts leds array to serial bit array.
Parameters
Leds input array. BitData is used as out
Definition at line 30 of file rgbw.c.
References Led_t::B, BitData, CCR_0, CCR_1, Led_t::G, NLEDS, Led_t::R, RESET_BITS, and Led_t::W.
Referenced by displayStrip().
displayStrip()
void displayStrip (Led_t *const Leds)
Sends data to the strip. Number of leds is NLEDS.
Parameters
Leds Pointer to the array of led data
Definition at line 85 of file rgbw.c.
References BitData, ConvertLeds(), tim2_set_data(), and tim2_TransferBits().
Referenced by sendDataToStrip().
Variable Documentation
BitData
uint8_t BitData[NLEDS *8 *4+RESET_BITS+1] static
Led array bits. Contains one byte for bit so each led takes 32bytes. Also RESET_BITS are added and one byte to switch the out off.
Definition at line 24 of file rgbw.c.
Referenced by ConvertLeds(), and displayStrip().