PitStick: timer_dma.h File Reference
timer_dma.h File Reference
Contains timer2+dma driver prototypes to send data to led strip.
Functions
void tim2_Init (void)
Initialization of tim2+dma.
void tim2_set_data (uint8_t *const addr, const uint16_t size)
Sets data to be sent.
void tim2_TransferBits (void)
Starts actual transfer.
Detailed Description
Contains timer2+dma driver prototypes to send data to led strip.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
21-11-2019
Version
1.00
Definition in file timer_dma.h.
Function Documentation
tim2_Init()
void tim2_Init (void)
Initialization of tim2+dma.
Definition at line 38 of file timer_dma.c.
References pin_init().
Referenced by Init().
tim2_set_data()
void tim2_set_data (uint8_t *const addr, const uint16_t size)
Sets data to be sent.
Parameters
addr bit array address
size bit array size
Definition at line 61 of file timer_dma.c.
References baddr, and bsize.
Referenced by displayStrip().
tim2_TransferBits()
void tim2_TransferBits (void)
Starts actual transfer.
Definition at line 70 of file timer_dma.c.
References baddr, and bsize.
Referenced by displayStrip().