PitStick: watchdog.c File Reference
watchdog.c File Reference
Contains independent watchdog init and functions.
#include "watchdog.h"
#include <stm32f1xx.h>
Macros
#define IWDG_KEY_START 0xCCCC
#define IWDG_KEY_UNLOCK 0x5555
#define IWDG_KEY_RESET 0xAAAA
Functions
void watchdog_Init (void)
Initialises and start wdt. Timeout is 1s.
void Reset_Watchdog (void)
Resets watchdog.
Detailed Description
Contains independent watchdog init and functions.
Author
Mikl Scherbak (mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om)
Date
02-05-2017
Version
1.0
Definition in file watchdog.c.
Macro Definition Documentation
IWDG_KEY_RESET
#define IWDG_KEY_RESET 0xAAAA
Definition at line 10 of file watchdog.c.
Referenced by Reset_Watchdog().
IWDG_KEY_START
#define IWDG_KEY_START 0xCCCC
Definition at line 8 of file watchdog.c.
Referenced by watchdog_Init().
IWDG_KEY_UNLOCK
#define IWDG_KEY_UNLOCK 0x5555
Definition at line 9 of file watchdog.c.
Referenced by watchdog_Init().
Function Documentation
Reset_Watchdog()
void Reset_Watchdog (void)
Resets watchdog.
Definition at line 25 of file watchdog.c.
References IWDG_KEY_RESET.
Referenced by main(), and MainLoop_Iteration().
watchdog_Init()
void watchdog_Init (void)
Initialises and start wdt. Timeout is 1s.
Definition at line 15 of file watchdog.c.
References IWDG_KEY_START, and IWDG_KEY_UNLOCK.
Referenced by Init().