PitStick: watchdog.h File Reference
watchdog.h File Reference
Contains independent watchdog init and functions prototypes.
Functions
void watchdog_Init (void)
Initialises and start wdt. Timeout is 1s.
void Reset_Watchdog (void)
Resets watchdog.
Detailed Description
Contains independent watchdog init and functions prototypes.
Author
Mikl Scherbak (mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om)
Date
02-05-2017
Version
1.0
Definition in file watchdog.h.
Function Documentation
Reset_Watchdog()
void Reset_Watchdog (void)
Resets watchdog.
Definition at line 25 of file watchdog.c.
References IWDG_KEY_RESET.
Referenced by main(), and MainLoop_Iteration().
watchdog_Init()
void watchdog_Init (void)
Initialises and start wdt. Timeout is 1s.
Definition at line 15 of file watchdog.c.
References IWDG_KEY_START, and IWDG_KEY_UNLOCK.
Referenced by Init().